server.port=8080
spring.datasource.url=jdbc:postgresql://smart-campus-24411.j77.aws-ap-south-1.cockroachlabs.cloud:26257/smartcampus?sslmode=require

spring.datasource.username=mufeezmujassir
spring.datasource.password=rwN7mQkfUGpWFl5ID6Mb6w
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Disable Flyway (using ddl-auto=update instead)
spring.flyway.enabled=false

# JWT Configuration
jwt.secret=dGhpcyBpcyBhIHZlcnkgc2VjdXJlIHNlY3JldCBrZXkgZm9yIHNtYXJ0IGNhbXB1cyBvcGVyYXRpb25zIGh1YiEhIQ==
jwt.access-token-expiration=900000
jwt.refresh-token-expiration=604800000

# Logging
logging.level.com.smartcampus.operations=DEBUG
spring.security.oauth2.client.registration.google.client-id=795020758337-4sseugghmtr5pp67ht9ej4ca8molgb4t.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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